---
title: "Public Health Class with R Markdown"
subtitle: "subtitle here"
author: "Dr Mohd Azmi (MBBS, MPH)"
institute: "Universiti Sains Malaysia, DrPH (Epidemiology) Candidate"
output:
  beamer_presentation:
    theme: "AnnArbor"
    colortheme: "dolphin"
    fonttheme: "structurebold"
    fig_width: 7
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Target Audience

Aim: Introductory

- Teaching Staff
- Student

Disclaimer

- Very simple slide
  - short learning curve
- Be creative!
- Try, try, try


## Motivation

- Statistic and Public Health
- Multiple output file for same purpose

## Teaching Statistic

- fast, reproducible

### <b>
x <- runif(100, 5, 10)

y <- sample(5:10, 100, replace = T)

y2 <- (x+y/2) 

fake <- data.frame(x,y,y2) 

with(fake, plot(x,y2))
</b>


## 

```{r}
x <- runif(100, 5, 10)
y <- sample(5:10, 100, replace = T)
y2 <- (x+y/2)
fake <- data.frame(x,y,y2)
with(fake, plot(x,y2))
```

## Tidyverse

- example using tidyverse

### <b>

tibble(x=runif(100, 5, 10),

y=sample(5:10, 100, replace = T),

y2 = (x+y/2)) %>%

ggplot(aes(x,y2)) + geom_point()
</b>

##

```{r}
tibble(x=runif(100, 5, 10), y=sample(5:10, 100, replace = T), y2 = (x+y/2)) %>% 
  ggplot(aes(x,y2)) + geom_point()
```



